// Wrong resources fix
ACTION_IF (FILE_CONTAINS_EVALUATED (~SPELL.IDS~ ~[ %TAB%]CLERIC_POLYMORPH_OTHER[ %TAB%%LNL%%MNL%%WNL%]~)) BEGIN // Periapt of Form Stability Druid Polymorph Other
  LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~CLERIC_POLYMORPH_OTHER~ RET spell_res END
  OUTER_SPRINT ~polymorph_other~ ~%spell_res%~
  ACTION_IF (FILE_EXISTS_IN_GAME ~amul24.itm~) THEN BEGIN
    COPY_EXISTING ~amul24.itm~ ~override~
      REPLACE_TEXTUALLY ~sppr420~ ~%polymorph_other%~
  END
END
ACTION_IF (FILE_CONTAINS_EVALUATED (~SPELL.IDS~ ~[ %TAB%]WIZARD_VITRIOLIC_SPHERE [ %TAB%%LNL%%MNL%%WNL%]~)) BEGIN // Protection from Acid scroll
  LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~WIZARD_VITRIOLIC_SPHERE~ RET spell_res END
  OUTER_SPRINT ~vitriolic_sphere~ ~%spell_res%~
  ACTION_IF (FILE_EXISTS_IN_GAME ~scrl03.spl~) THEN BEGIN
    COPY_EXISTING ~scrl03.spl~ ~override~
      // LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=2 duration=300 resist_dispel=3 STR_VAR resource=~%vitriolic_sphere%~ END
  END
END
ACTION_IF (FILE_CONTAINS_EVALUATED (~SPELL.IDS~ ~[ %TAB%]CLERIC_ICE_STORM [ %TAB%%LNL%%MNL%%WNL%]~)) BEGIN // Protection from Cold scroll
  LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~CLERIC_ICE_STORM~ RET spell_res END
  OUTER_SPRINT ~ice_storm~ ~%spell_res%~
  ACTION_IF (FILE_EXISTS_IN_GAME ~scrl04.spl~) THEN BEGIN
    COPY_EXISTING ~scrl04.spl~ ~override~
      // LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=2 duration=300 resist_dispel=3 STR_VAR resource=~%ice_storm%~ END
      LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=2 duration=300 resist_dispel=3 STR_VAR resource=spdr501 END
  END
END
/* ACTION_IF (FILE_CONTAINS_EVALUATED (~SPELL.IDS~ ~[ %TAB%]WIZARD_BALL_LIGHTNING [ %TAB%%LNL%%MNL%%WNL%]~)) BEGIN // Protection from Lightning scroll
  LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~WIZARD_BALL_LIGHTNING~ RET spell_res END
  OUTER_SPRINT ~ball_lightning~ ~%spell_res%~ */
  ACTION_IF (FILE_EXISTS_IN_GAME ~scrl05.spl~) THEN BEGIN
    COPY_EXISTING ~scrl05.spl~ ~override~
      // LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=2 duration=300 resist_dispel=3 STR_VAR resource=~%ball_lightning%~ END
      LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=2 duration=300 resist_dispel=3 STR_VAR resource=spwi615d END
      LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=2 duration=300 resist_dispel=3 STR_VAR resource=spdr601 END
      LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=2 duration=300 resist_dispel=3 STR_VAR resource=spdr601d END
  END
//  END
ACTION_IF (FILE_CONTAINS_EVALUATED (~SPELL.IDS~ ~[ %TAB%]CLERIC_FIRE_TRAP [ %TAB%%LNL%%MNL%%WNL%]~)) BEGIN // Protection from Fire scroll
  LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~CLERIC_FIRE_TRAP~ RET spell_res END
  OUTER_SPRINT ~fire_trap~ ~%spell_res%~
  ACTION_IF (FILE_EXISTS_IN_GAME ~scrl06.spl~) THEN BEGIN
    COPY_EXISTING ~scrl06.spl~ ~override~
      // LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=2 duration=300 resist_dispel=3 STR_VAR resource=~%fire_trap%~ END
  END
END

// Item description updates
ACTION_IF (FILE_EXISTS_IN_GAME ~brac23.itm~) THEN BEGIN
COPY_EXISTING ~brac23.itm~ ~override~
  SPRINT old_spell_name @1308000 // Righteous Magic
  SPRINT new_spell_name @130800 // Righteous Fury
  TEXT_SPRINT text_update ~replace_spell_name~
  LPM ~update_item_descriptions~
END
ACTION_IF (FILE_EXISTS_IN_GAME ~hamm03.itm~) THEN BEGIN
COPY_EXISTING ~hamm03.itm~ ~override~
  SPRINT old_spell_name @1550000 // 4D4
  SPRINT new_spell_name @155000 // 5D4
  TEXT_SPRINT text_update ~replace_spell_name~
  LPM ~update_item_descriptions~
END
ACTION_IF (FILE_EXISTS_IN_GAME ~hamm11.itm~) THEN BEGIN
COPY_EXISTING ~hamm11.itm~ ~override~
  SPRINT old_spell_name @1566000 // Champion's Strength (1x per day): +5 bonus for 1 turn
  SPRINT new_spell_name @156600 // Champion's Strength (1x per day): +6 bonus for 1 turn
  TEXT_SPRINT text_update ~replace_spell_name~
  LPM ~update_item_descriptions~
  SPRINT old_spell_name @156600000 // Champion's Strength (1x per day): +5 bonus for 1 turn
  SPRINT new_spell_name @15660000
  TEXT_SPRINT text_update ~replace_spell_name~
  LPM ~update_item_descriptions~
END
ACTION_IF (FILE_EXISTS_IN_GAME ~misc3a12.itm~) THEN BEGIN
COPY_EXISTING ~misc3a8.itm~ ~override~
  SPRINT old_spell_name @1699000 // Animate Dead
  SPRINT new_spell_name @169900 // Summon Shadow
  TEXT_SPRINT text_update ~replace_spell_name~
  LPM ~update_item_descriptions~
END
ACTION_IF (FILE_EXISTS_IN_GAME ~misc3h.itm~) THEN BEGIN
COPY_EXISTING ~misc3h.itm~ ~override~
  SPRINT old_spell_name @1550000 // 4D4
  SPRINT new_spell_name @155000 // 5D4
  TEXT_SPRINT text_update ~replace_spell_name~
  LPM ~update_item_descriptions~
END
ACTION_IF (FILE_EXISTS_IN_GAME ~misc3l.itm~) THEN BEGIN
COPY_EXISTING ~misc3l.itm~ ~override~
  SPRINT old_spell_name @1723000 // Silence 15' Radius
  SPRINT new_spell_name @172300 // Silence
  TEXT_SPRINT text_update ~replace_spell_name~
  LPM ~update_item_descriptions~
  SPRINT old_spell_name @1723010 // (3x per day): opponents within 15' are silenced for 1 turn (save vs. spell at -4 neg.)
  SPRINT new_spell_name @172301 // (3x per day): opponents within 20' are silenced for 1 turn (save vs. spell at -4 neg.)
  TEXT_SPRINT text_update ~replace_spell_name~
  LPM ~update_item_descriptions~
  SPRINT old_spell_name @172301000
  SPRINT new_spell_name @17230100
  TEXT_SPRINT text_update ~replace_spell_name~
  LPM ~update_item_descriptions~
END
ACTION_IF (FILE_EXISTS_IN_GAME ~npshld.itm~) THEN BEGIN
COPY_EXISTING ~npshld.itm~ ~override~
  SPRINT old_spell_name @1805000 // Protection from Normal Missiles
  SPRINT new_spell_name @180500 // Protection from Missiles
  TEXT_SPRINT text_update ~replace_spell_name~
  LPM ~update_item_descriptions~
END
ACTION_IF (FILE_EXISTS_IN_GAME ~ring39.itm~) THEN BEGIN
COPY_EXISTING ~ring39.itm~ ~override~
  SPRINT old_spell_name @1903000 // Energy Drain
  SPRINT new_spell_name @190300 // Larloch's Energy Drain
  TEXT_SPRINT text_update ~replace_spell_name~
  LPM ~update_item_descriptions~
END
ACTION_IF (FILE_EXISTS_IN_GAME ~slng06.itm~) THEN BEGIN
COPY_EXISTING ~slng06.itm~ ~override~
  SPRINT old_spell_name @1550000 // 4D4
  SPRINT new_spell_name @155000 // 5D4
  TEXT_SPRINT text_update ~replace_spell_name~
  LPM ~update_item_descriptions~
END
ACTION_IF (FILE_EXISTS_IN_GAME ~staf22.itm~) THEN BEGIN
COPY_EXISTING ~staf22.itm~ ~override~
  SPRINT old_spell_name @2049000 // 2D6
  SPRINT new_spell_name @204900 // 2D8
  TEXT_SPRINT text_update ~replace_spell_name~
  LPM ~update_item_descriptions~
END
ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h65.itm~) THEN BEGIN
COPY_EXISTING ~sw1h65.itm~ ~override~
  SPRINT old_spell_name @2162000 // Draw Upon Holy Might
  SPRINT new_spell_name @216200 // Draw Upon Divine Might
  TEXT_SPRINT text_update ~replace_spell_name~
  LPM ~update_item_descriptions~
END
ACTION_IF (FILE_EXISTS_IN_GAME ~wand10.itm~) THEN BEGIN
COPY_EXISTING ~wand10.itm~ ~override~
  SPRINT old_spell_name @2258000 // Monster Summoning
  SPRINT new_spell_name @225800 // Monster Summoning IV
  TEXT_SPRINT text_update ~replace_spell_name~
  LPM ~update_item_descriptions~
END

// Spell name updates
ACTION_IF (FILE_EXISTS_IN_GAME ~misc3l.spl~) THEN BEGIN
  COPY_EXISTING ~misc3l.spl~ ~override~ // Silence
    SAY NAME2 @172300
END

// SRR spell updates
COPY ~spell_rev\shared\item_rev\dvbram.spl~   ~override~ // Battering Ram
COPY ~spell_rev\shared\item_rev\dvmcure.spl~  ~override~ // Mass Cure
  WRITE_SHORT 0x98 %dvmscure%
  SAY NAME1 @177
ADD_PROJECTILE ~spell_rev\shared\item_rev\dvpexpl.pro~
COPY ~spell_rev\shared\item_rev\dvpexpl.spl~  ~override~ // Prismatic Explosion
  WRITE_SHORT 0x98 %dvpexpl%
  SAY NAME1 @401400
COPY ~spell_rev\shared\item_rev\dvdomina.spl~ ~override~ // Domination
  SAY NAME1 @621
COPY ~spell_rev\shared\item_rev\dvreson.spl~  ~override~ // Resonating
  WRITE_SHORT 0x98 %dvsndbr%
COPY ~spell_rev\shared\item_rev\dvsburst.spl~ ~override~ // Sonic Blast
  WRITE_SHORT 0x98 %dvsndbr%
COPY ~spell_rev\shared\item_rev\hamm11.spl~   ~override~ // Champion's Strength
  SAY NAME1 @163
COPY ~spell_rev\shared\item_rev\misc3l.spl~   ~override~ // Silence
  WRITE_SHORT 0x98 %dvsilenc%
  SAY NAME1 @51
COPY ~spell_rev\shared\item_rev\npshld.spl~   ~override~ // Protection from Missiles
  SAY NAME1 @180500
COPY ~spell_rev\shared\item_rev\misc3c.eff~   ~override~ // Summon Efreeti
ACTION_IF slowing_web=1 BEGIN
COPY ~spell_rev\shared\alternatives\wand14.spl~   ~override~ // Web
  SAY NAME1 @477
END ELSE BEGIN
COPY ~spell_rev\shared\item_rev\wand14.spl~   ~override~ // Web
  SAY NAME1 @477
END

ACTION_IF dispel_globes=2 BEGIN
  COPY ~spell_rev\shared\item_rev\misc73n.spl~     ~override\misc73.spl~  // Globe of Power
  COPY ~spell_rev\shared\item_rev\dvginvuln.spl~   ~override\dvginvul.spl~  // Globe of Invulnerability
END ELSE ACTION_IF dispel_globes=0 BEGIN
  COPY ~spell_rev\shared\item_rev\misc73d.spl~     ~override\misc73.spl~  // Globe of Power
  COPY ~spell_rev\shared\item_rev\dvginvuld.spl~   ~override\dvginvul.spl~  // Globe of Invulnerability
END

// Fix tooltips
LAF tooltips INT_VAR
  $tip(1) = RESOLVE_STR_REF (@130800)
STR_VAR
  item = brac23
END
LAF tooltips INT_VAR
  $tip(1) = RESOLVE_STR_REF (@169900)
STR_VAR
  item = misc3a12
END
LAF tooltips INT_VAR
  $tip(1) = RESOLVE_STR_REF (@172300)
STR_VAR
  item = misc3l
END
LAF tooltips INT_VAR
  $tip(1) = RESOLVE_STR_REF (@180500)
STR_VAR
  item = npshld
END
LAF tooltips INT_VAR
  $tip(1) = RESOLVE_STR_REF (@1903000)
STR_VAR
  item = ring39
END
LAF tooltips INT_VAR
  $tip(2) = RESOLVE_STR_REF (@216200)
STR_VAR
  item = sw1h65
END

// Projectile protections

ACTION_IF (FILE_EXISTS_IN_GAME ~arowex.pro~) BEGIN // Arrow of Detonation
ADD_PROJECTILE ~item_rev/itm/arowex.pro~

ACTION_IF (FILE_EXISTS_IN_GAME ~spra303.spl~) BEGIN
COPY_EXISTING ~spra303.spl~      ~override~  // Protection from Missiles
PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
  SET "loop" = 1
  WHILE (%loop% < 37) BEGIN
  SET opcode = 83
  SET target = 1
  SET timing = 0
  SET power = 6
  SET resist_dispel = 3
  SET duration = (84 + (%loop% * 6))
  SET probability1 = 100
  SET probability2 = 0
  SPRINT "resource" ""
  SET dicenumber = 0
  SET dicesize = 0
  SET savingthrow = 0
  SET savebonus = 0
  SET parameter1 = 0
  SET parameter2 = (%arowex% - 1)
  SET header = %loop%
  LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
  SET "loop" = %loop% + 1
END END END

ACTION_IF (FILE_EXISTS_IN_GAME ~sppr613.spl~) BEGIN
COPY_EXISTING ~sppr613.spl~     ~override~  // Physical Mirror
PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
  SET "loop" = 1
  WHILE (%loop% < 31) BEGIN
  SET opcode = 83
  SET target = 1
  SET timing = 0
  SET power = 6
  SET resist_dispel = 3
  SET duration = (120 + (%loop% * 6))
  SET probability1 = 100
  SET probability2 = 0
  SPRINT "resource" ""
  SET dicenumber = 0
  SET dicesize = 0
  SET savingthrow = 0
  SET savebonus = 0
  SET parameter1 = 0
  SET parameter2 = (%arowex% - 1)
  SET header = %loop%
  LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
  SET "loop" = %loop% + 1
END END END

ACTION_IF (FILE_EXISTS_IN_GAME ~spwi311.spl~) BEGIN
COPY_EXISTING ~spwi311.spl~     ~override~  // Protection from Missiles
PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
  SET "loop" = 1
  WHILE (%loop% < 37) BEGIN
  SET opcode = 83
  SET target = 1
  SET timing = 0
  SET power = 6
  SET resist_dispel = 3
  SET duration = (84 + (%loop% * 6))
  SET probability1 = 100
  SET probability2 = 0
  SPRINT "resource" ""
  SET dicenumber = 0
  SET dicesize = 0
  SET savingthrow = 0
  SET savebonus = 0
  SET parameter1 = 0
  SET parameter2 = (%arowex% - 1)
  SET header = %loop%
  LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
  SET "loop" = %loop% + 1
END END END

ACTION_IF (FILE_EXISTS_IN_GAME ~npshld.spl~) BEGIN
COPY_EXISTING ~npshld.spl~     ~override~  // Protection from Missiles
PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
  SET "loop" = 1
  WHILE (%loop% < 2) BEGIN
  SET opcode = 83
  SET target = 1
  SET timing = 0
  SET power = 6
  SET resist_dispel = 3
  SET duration = (54 + (%loop% * 6))
  SET probability1 = 100
  SET probability2 = 0
  SPRINT "resource" ""
  SET dicenumber = 0
  SET dicesize = 0
  SET savingthrow = 0
  SET savebonus = 0
  SET parameter1 = 0
  SET parameter2 = (%arowex% - 1)
  SET header = %loop%
  LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
  SET "loop" = %loop% + 1
END END END

ACTION_FOR_EACH resource IN
  ~brac18~   // Gloves of Missile Snaring
  ~shld24~   // Reflection Shield
BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%resource%.itm~) BEGIN
    COPY_EXISTING ~%resource%.itm~ ~override\%resource%.itm~
    PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
SET opcode = 83            // Set opcode
SET target = 1            // target type
SET timing = 2            // timing type
SET power = 0            // power
SET resist_dispel = 0    // dispel/resitance
SET duration = 0        // duration
SET probability1 = 100    // probability 1
SET probability2 = 0    // probability 2
SPRINT "resource" ""         // resource
SET dicenumber = 0        // dice number
SET dicesize = 0        // dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0        // saving throw bonus
SET parameter1 = 0 // param1
SET parameter2 = (%arowex% - 1) // param2
LAUNCH_PATCH_MACRO ADD_ITEM_EQEFFECT
    END    BUT_ONLY_IF_IT_CHANGES
  END
END

END // Arow of Detonation

ACTION_IF (FILE_EXISTS_IN_GAME ~bow19.pro~) BEGIN // Lightning Spear
ADD_PROJECTILE ~item_rev/itm/bow19.pro~

ACTION_IF (FILE_EXISTS_IN_GAME ~spra303.spl~) BEGIN
COPY_EXISTING ~spra303.spl~      ~override~  // Protection from Missiles
PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
  SET "loop" = 1
  WHILE (%loop% < 37) BEGIN
  SET opcode = 83
  SET target = 1
  SET timing = 0
  SET power = 6
  SET resist_dispel = 3
  SET duration = (84 + (%loop% * 6))
  SET probability1 = 100
  SET probability2 = 0
  SPRINT "resource" ""
  SET dicenumber = 0
  SET dicesize = 0
  SET savingthrow = 0
  SET savebonus = 0
  SET parameter1 = 0
  SET parameter2 = (%bow19% - 1)
  SET header = %loop%
  LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
  SET "loop" = %loop% + 1
END END END

ACTION_IF (FILE_EXISTS_IN_GAME ~sppr613.spl~) BEGIN
COPY_EXISTING ~sppr613.spl~     ~override~  // Physical Mirror
PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
  SET "loop" = 1
  WHILE (%loop% < 31) BEGIN
  SET opcode = 83
  SET target = 1
  SET timing = 0
  SET power = 6
  SET resist_dispel = 3
  SET duration = (120 + (%loop% * 6))
  SET probability1 = 100
  SET probability2 = 0
  SPRINT "resource" ""
  SET dicenumber = 0
  SET dicesize = 0
  SET savingthrow = 0
  SET savebonus = 0
  SET parameter1 = 0
  SET parameter2 = (%bow19% - 1)
  SET header = %loop%
  LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
  SET "loop" = %loop% + 1
END END END

ACTION_IF (FILE_EXISTS_IN_GAME ~spwi311.spl~) BEGIN
COPY_EXISTING ~spwi311.spl~     ~override~  // Protection from Missiles
PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
  SET "loop" = 1
  WHILE (%loop% < 37) BEGIN
  SET opcode = 83
  SET target = 1
  SET timing = 0
  SET power = 6
  SET resist_dispel = 3
  SET duration = (84 + (%loop% * 6))
  SET probability1 = 100
  SET probability2 = 0
  SPRINT "resource" ""
  SET dicenumber = 0
  SET dicesize = 0
  SET savingthrow = 0
  SET savebonus = 0
  SET parameter1 = 0
  SET parameter2 = (%bow19% - 1)
  SET header = %loop%
  LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
  SET "loop" = %loop% + 1
END END END

ACTION_IF (FILE_EXISTS_IN_GAME ~npshld.spl~) BEGIN
COPY_EXISTING ~npshld.spl~     ~override~  // Protection from Missiles
PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
  SET "loop" = 1
  WHILE (%loop% < 2) BEGIN
  SET opcode = 83
  SET target = 1
  SET timing = 0
  SET power = 6
  SET resist_dispel = 3
  SET duration = (54 + (%loop% * 6))
  SET probability1 = 100
  SET probability2 = 0
  SPRINT "resource" ""
  SET dicenumber = 0
  SET dicesize = 0
  SET savingthrow = 0
  SET savebonus = 0
  SET parameter1 = 0
  SET parameter2 = (%bow19% - 1)
  SET header = %loop%
  LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
  SET "loop" = %loop% + 1
END END END

ACTION_FOR_EACH resource IN
  ~brac18~   // Gloves of Missile Snaring
  ~shld24~   // Reflection Shield
BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%resource%.itm~) BEGIN
    COPY_EXISTING ~%resource%.itm~ ~override\%resource%.itm~
    PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
SET opcode = 83            // Set opcode
SET target = 1            // target type
SET timing = 2            // timing type
SET power = 0            // power
SET resist_dispel = 0    // dispel/resitance
SET duration = 0        // duration
SET probability1 = 100    // probability 1
SET probability2 = 0    // probability 2
SPRINT "resource" ""         // resource
SET dicenumber = 0        // dice number
SET dicesize = 0        // dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0        // saving throw bonus
SET parameter1 = 0 // param1
SET parameter2 = (%bow19% - 1) // param2
LAUNCH_PATCH_MACRO ADD_ITEM_EQEFFECT
    END    BUT_ONLY_IF_IT_CHANGES
  END
END

END // Lightning Spear

ACTION_FOR_EACH resource IN
  ~brac18~   // Gloves of Missile Snaring
  ~shld24~   // Reflection Shield
BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%resource%.itm~) BEGIN
    COPY_EXISTING ~%resource%.itm~ ~override\%resource%.itm~
    PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
SET opcode = 83            // Set opcode
SET target = 1            // target type
SET timing = 2            // timing type
SET power = 0            // power
SET resist_dispel = 0    // dispel/resitance
SET duration = 0        // duration
SET probability1 = 100    // probability 1
SET probability2 = 0    // probability 2
SPRINT "resource" ""         // resource
SET dicenumber = 0        // dice number
SET dicesize = 0        // dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0        // saving throw bonus
SET parameter1 = 0 // param1
SET parameter2 = (%dvfarrow% - 1) // param2
LAUNCH_PATCH_MACRO ADD_ITEM_EQEFFECT
    END    BUT_ONLY_IF_IT_CHANGES
  END
END