INCLUDE ~spell_rev\lib\manage_add_spell_references.tpa~

LAF GET_NEW_SPELL_RESREFS RET_ARRAY new_spell_resrefs END

OUTER_TEXT_SPRINT sppr116 $new_spell_resrefs(~sppr116~)
OUTER_TEXT_SPRINT sppr121 $new_spell_resrefs(~sppr121~)
OUTER_TEXT_SPRINT sppr216 $new_spell_resrefs(~sppr216~)
OUTER_TEXT_SPRINT sppr311 $new_spell_resrefs(~sppr311~)
OUTER_TEXT_SPRINT sppr325 $new_spell_resrefs(~sppr325~)
OUTER_TEXT_SPRINT sppr326 $new_spell_resrefs(~sppr326~)
OUTER_TEXT_SPRINT sppr418 $new_spell_resrefs(~sppr418~)
OUTER_TEXT_SPRINT spwi327 $new_spell_resrefs(~spwi327~)
OUTER_TEXT_SPRINT spwi427 $new_spell_resrefs(~spwi427~)

//kjernon's code 

DEFINE_ACTION_FUNCTION	ADD_SPLPROT	INT_VAR	stat = 0	value = 0	relation = 0	RET	new_row		BEGIN
	ACTION_IF	(stat > 278)	BEGIN	WARN	~SPLPROT.2DA - Stat out of Bounds.~	END
	ACTION_IF	((stat != 259) AND (stat != 260) AND (relation > 11))	BEGIN	WARN	~SPLPROT.2DA - Relation out of Bounds.~	END
	COPY_EXISTING ~SPLPROT.2DA~	~override~
		COUNT_2DA_COLS	cols
		COUNT_2DA_ROWS cols rows
		TEXT_SPRINT check_row ~~
		TEXT_SPRINT check_stat ~~
		SET new_row = 0
		FOR(current_row = 0; current_row < rows; ++current_row)	BEGIN	READ_2DA_ENTRY current_row 1 cols check_stat
			PATCH_IF (~%check_stat%~ STRING_EQUAL ~%stat%~)	BEGIN	READ_2DA_ENTRY current_row 2 cols check_value
				PATCH_IF (~%check_value%~ STRING_EQUAL ~%value%~)	BEGIN	READ_2DA_ENTRY current_row 3 cols check_relation
					PATCH_IF (~%check_relation%~ STRING_EQUAL ~%relation%~)	BEGIN	new_row = current_row	current_row = rows	END
				END
			END
		END
		PATCH_IF (new_row = 0)	BEGIN
			FOR(current_row = 0; current_row < rows; ++current_row)	BEGIN	READ_2DA_ENTRY current_row 1 cols check_stat
				PATCH_IF (~%check_stat%~ STRING_EQUAL ~*~)	BEGIN	new_row = current_row	current_row = rows	END
			END
			PATCH_IF (new_row = 0)	BEGIN	new_row = rows	INSERT_2DA_ROW rows cols ~%new_row%		   %stat%		   %value%		   %relation%~
			END	ELSE	BEGIN	SET_2DA_ENTRY new_row 1 cols ~%stat%~	SET_2DA_ENTRY new_row 2 cols ~%value%~	SET_2DA_ENTRY new_row 3 cols ~%relation%~	END
		END
	BUT_ONLY
END
//	Array of Restistance / Stat#
ACTION_DEFINE_ASSOCIATIVE_ARRAY	DMG_ARRAY	BEGIN
	~CRUSH~		=>	22
	~ACID~		=>	17
	~COLD~		=>	15
	~ELEC~		=>	16
	~FIRE~		=>	14
	~PIERC~		=>	23
	~POISN~		=>	74
	~MAGIC~		=>	73
	~MSSL~		=>	24
	~SLASH~		=>	21
	~MFIRE~		=>	19
	~MCOLD~		=>	20
END
ACTION_PHP_EACH	DMG_ARRAY AS one => two	BEGIN
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 100	relation = 	2	RET	min = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 128	relation = 	4	RET	max = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = 260	value = min	relation = 	max	RET	EVAL ~%one%~ = new_row	END
END
// Sets a variable, named after the string (CRUSH, ACID, COLD, etc..) to the row# to be used for opcode 324/318.  For each spell you would do something like this: // 

// FIRE IMMUNITY//

	COPY_EXISTING	~bdpflame.spl~	override		// produce flame
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~bdsha12a.spl~	override		// ??
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~bdshld02.spl~	override		// fire attack from shield
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~ohbeflam.spl~	override		// flames!
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~balshld2.spl~	override		// some balthy crp
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~balth01b.spl~	override		// balthazar fireshield
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spcl236.spl~	override		// sun soul monk soulray
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spcl237d.spl~	override		// sun soul monk fireshield
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spcl237d.spl~	override		// sun soul monk fireshield
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spcl239a.spl~	override		// sun soul monk blinding attack, assuming fire causes blindness
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spdd03.spl~	override		// dragon disciple breath attack
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
		COPY_EXISTING	~spctmd01.spl~	override		//fireball
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spin539.spl~	override		//magma bolt
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

	COPY_EXISTING	~spin160.spl~	override		// salamander fire
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spin560.spl~	override		// Cinder Shower
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spin561.spl~	override		// fire giant lava attack
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

	COPY_EXISTING	~spin567.spl~	override		// mimic fire
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS


COPY_EXISTING	~spin819.spl~	override		// Lava burst
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spin885.spl~	override		// kamikaze explosion
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	
	COPY_EXISTING	~spin894.spl~	override		// Red dragon breath
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spin926.spl~	override		// water jet (fire damage, steam or whatever)
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

	COPY_EXISTING	~spin930.spl~	override		// mephit lava
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spin938.spl~	override		//  Flame fan
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

	COPY_EXISTING	~spin939.spl~	override		//  Flame jet
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spin956.spl~	override		//  Hell hound flame breath
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spin987.spl~	override		//  Beholder scorcher
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~%sppr114%.spl~	override		//  sunscorch
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
		COPY_EXISTING	~%sppr216%.spl~	override		//  Fire trap
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~sppr503.spl~	override		//  Flamestrike
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

	COPY_EXISTING	~sppr705.spl~	override		//  Firestorm
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS


COPY_EXISTING	~sppr730d.spl~	override		//  Flaming death aura
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~sppr952d.spl~	override		//  some fireshield
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~sppr985.spl~	override		//  Flamestrike trap
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spwi001.spl~	override		//  fireball trap
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS


COPY_EXISTING	~spwi022.spl~	override		//  muck(!) trap, fire damage
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi103.spl~	override		//  burning hands
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi217.spl~	override		//  Aganaza scorcher
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi303.spl~	override		// flame arrow
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spwi303a.spl~	override		// flame arrow
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spwi303b.spl~	override		// flame arrow
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spwi303c.spl~	override		// flame arrow
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spwi303d.spl~	override		// flame arrow
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY 
	
	COPY_EXISTING	~spwi303e.spl~	override		// flame arrow
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi304.spl~	override		// fireball
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi418d.spl~	override		// fireshield red
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi523.spl~	override		// sunfire
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spwi523d.spl~	override		// sunfire
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi712.spl~	override		// Delayed blast fireball
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi810.spl~	override		// incendiary cloud
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spwi911.spl~	override		// Meteor swarm
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi922.spl~	override		// Dragon's Breath
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS


	COPY_EXISTING	~spwi940.spl~	override		// Firedrake attack
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi957.spl~	override		// "RED" Fireball
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi979.spl~	override		// sarevok flamestrike - check if buggy or what
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwish24.spl~	override		// meteor swarm on caster
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	
COPY_EXISTING	~ohbwi304.spl~	override		// fireball
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

////COLD IMMUNITY//


COPY_EXISTING	~ohbicew.spl~	override		// wall of ice, does crushing as well but assuming it's from cold blocks
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~1tarss.spl~	override		// cold fireshield (???)
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spcryo01.spl~	override		// cryonax cone of cold
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spcryod.spl~	override		// cryonax fireshield
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
COPY_EXISTING	~spin562.spl~	override		// scalding steam
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

	
	COPY_EXISTING	~spin723.spl~	override		// Dragon rain (cold, can slay but assuming slays by ice)
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spin833.spl~	override		// Silver dragon cold attack
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spin936.spl~	override		// Mephit ice shard
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~%sppr418%.spl~	override		// ice storm druid
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
			COPY_EXISTING	~spdr501.spl~	override		// cone of cold avenger
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS


	
	COPY_EXISTING	~sppr951d.spl~	override		// Fireshield
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spwi015.spl~	override		// trap cold
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spwi018.spl~	override		// trap cold
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
		COPY_EXISTING	~%spwi327%.spl~	override		// icelance
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~%sppr326%.spl~	override		// icelance druid
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi403d.spl~	override		// cold fireshield
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

	COPY_EXISTING	~spwi404.spl~	override		// ice storm
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spwi503.spl~	override		// cone of cold
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~ubsnobr.spl~	override		// snow golem frost ray
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
		COPY_EXISTING	~spwi818.spl~	override		// icy grasp
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
			COPY_EXISTING	~spwi818d.spl~	override		// icy grasp
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS



//// ELECTRIC IMMUNITY //

COPY_EXISTING	~spcl722.spl~	override		// Talos lighting bolt
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spdr301.spl~	override		//  avenger lighting bolt
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spdr601.spl~	override		//  avenger lighting bolt
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spin579.spl~	override		// power amp
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
COPY_EXISTING	~spin597.spl~	override		// blue dragon lighting attack
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spin714.spl~	override		//  clestial bolt
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spin932.spl~	override		//  mephit lighting bolt
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spin933.spl~	override		//  mephit lighting bolt
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~sppr302.spl~	override		// call lighting
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~sppr304.spl~	override		// glyph of warding
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~sppr987.spl~	override		// call lighting trap
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi002.spl~	override		//  lighting trap
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi017.spl~	override		// minor lighting trap
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi025.spl~	override		// lighting orb
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi026.spl~	override		// lighting orb 2
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi027.spl~	override		// orb 3
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi308.spl~	override		// lighting bolt
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi615.spl~	override		// chain lighting
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spwi615a.spl~	override		// chain lighting
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spwi615b.spl~	override		// chain lighting
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~bdhalb01.spl~	override		// some halberd from sod
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~ohbcalll.spl~	override		// ???
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	
	COPY_EXISTING	~ohbwi308.spl~	override		// lighting bolt
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

///// ACID IMMUNITY //


	COPY_EXISTING	~ohdmask.spl~	override		// mask attack yea
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ACID
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
		COPY_EXISTING	~ohrgrog.spl~	override		// ??
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ACID
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~bdmepwat.spl~	override		// ???
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ACID
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spin596.spl~	override		// brown dragon acid breath
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ACID
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spin691.spl~	override		// black dragon breath
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ACID
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
COPY_EXISTING	~spin708.spl~	override		// slime trap
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ACID
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spin913.spl~	override		// Mimic Acid
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ACID
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spin917.spl~	override		// Mane gas
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ACID
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi211.spl~	override		// Acid arrow
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ACID
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~%spwi427%.spl~	override		// vitriolic sphere
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ACID
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~dvwi526d.spl~	override		// mestil
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ACID
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi614.spl~	override		// death fog - it will no longer kill summons acid-immune!
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ACID
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS


///  MAGIC DAMAGE IMMUNITY // 


COPY_EXISTING	~keldorn.spl~	override		// keldorn's armor 
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spin202.spl~	override		// wounds
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

		COPY_EXISTING	~spin551.spl~	override		// wounds
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spin958.spl~	override		// wounds
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~spin986.spl~	override		// wounds
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	
COPY_EXISTING	~spin564.spl~	override		// skull trap exp
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spin912.spl~	override		// psi detonate
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spin962.spl~	override		// beholder magic missile
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~sppr313.spl~	override		// holy  smite
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~sppr314.spl~	override		// blight
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS


COPY_EXISTING	~sppr612.spl~	override		// bolt of glory
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

 
COPY_EXISTING	~spwi003.spl~	override		// mm trap
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi112.spl~	override		//mm trap
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

//ACTION_IF FILE_EXISTS_IN_GAME ~spwi119a.spl~ THEN BEGIN // This is LMD. AAAAAAAARGH!
/*COPY_EXISTING ~spwi119a.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 0
	parameter2		= 83
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi119a
END
END  */

COPY_EXISTING	~spwi313.spl~	override		// skull trap
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS 

COPY_EXISTING	~spwi616.spl~	override		// disintegrate
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi812.spl~	override		// adhw
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi950.spl~	override		// skull trap
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwi953.spl~	override		// dradael blue firaball
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

COPY_EXISTING	~spwish32.spl~	override		// Wish ADHW
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = MAGIC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

// POISON IMMUNITY //

COPY_EXISTING	~bdmucou2.spl~	override		// mucus
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = POISN
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
	COPY_EXISTING	~drgrbrht.spl~	override		// poison breath
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = POISN
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

	COPY_EXISTING	~bhaal2b.spl~	override		// poison ability from Ascension
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = POISN
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS


	COPY_EXISTING	~spin506.spl~	override		// neothelid poison breath
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = POISN
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
		COPY_EXISTING	~spin568.spl~	override		// mimic poison
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = POISN
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS



	COPY_EXISTING	~spin642.spl~	override		// poison cloud
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = POISN
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

	COPY_EXISTING	~spin673.spl~	override		// spore death
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = POISN
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

	COPY_EXISTING	~spin927.spl~	override		// boiling rain storm, stun and poison damage, assume stun is from poison
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = POISN
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

	COPY_EXISTING	~sppr411.spl~	override		// priest posion
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = POISN
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS
	
		COPY_EXISTING	~spwi016.spl~	override		// cloudkill trap
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = POISN
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS



	COPY_EXISTING	~spwi502.spl~	override		// cloudkill
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = POISN
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

	COPY_EXISTING	~bdleat05.spl~	override		//   posion backlash?
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = POISN
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
	BUT_ONLY IF_EXISTS

/// FREE ACTION //

ACTION_IF FILE_EXISTS_IN_GAME ~bdsha06b.spl~ THEN BEGIN
COPY_EXISTING ~bdsha06b.spl~ ~override~   // some slow
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = bdsha06b
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdshamb.spl~ THEN BEGIN
COPY_EXISTING ~bdshamb.spl~ ~override~   // entangling attack - shouldn't work vs FA, nor AC penalty (assume AC malus is from ent)
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = bdshamb
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbow06.spl~ THEN BEGIN
COPY_EXISTING ~bdbow06.spl~ ~override~   // entangling attack - shouldn't work vs FA, nor AC penalty (assume AC malus is from ent)
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = bdbow06
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~bddcor01.spl~ THEN BEGIN
COPY_EXISTING ~bddcor01.spl~ ~override~   // some stun
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = bddcor01
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdhalb03.spl~ THEN BEGIN
COPY_EXISTING ~bdhalb03.spl~ ~override~   // halberd
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = bdhalb03
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdhelm17.spl~ THEN BEGIN
COPY_EXISTING ~bdhelm17.spl~ ~override~   // halberd
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = bdhelm17
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdimpale.spl~ THEN BEGIN
COPY_EXISTING ~bdimpale.spl~ ~override~   // halberd
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = bdimpale
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdspidga.spl~ THEN BEGIN
COPY_EXISTING ~bdspidga.spl~ ~override~   // web tangle
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = bdspidga
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi101.spl~ THEN BEGIN
COPY_EXISTING ~spwi101.spl~ ~override~   // grease
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi101
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spdr201.spl~ THEN BEGIN
COPY_EXISTING ~spdr201.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spdr201
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin504.spl~ THEN BEGIN
COPY_EXISTING ~spin504.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin504
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin566.spl~ THEN BEGIN
COPY_EXISTING ~spin566.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin566
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin575.spl~ THEN BEGIN
COPY_EXISTING ~spin575.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin575
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin683.spl~ THEN BEGIN
COPY_EXISTING ~spin683.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin683
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin688.spl~ THEN BEGIN
COPY_EXISTING ~spin688.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin688
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin832.spl~ THEN BEGIN
COPY_EXISTING ~spin832.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin832
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin909.spl~ THEN BEGIN
COPY_EXISTING ~spin832.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin909
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin914.spl~ THEN BEGIN
COPY_EXISTING ~spin914.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin914
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin960.spl~ THEN BEGIN
COPY_EXISTING ~spin960.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin960
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin977.spl~ THEN BEGIN
COPY_EXISTING ~spin977.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin977
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin983.spl~ THEN BEGIN
COPY_EXISTING ~spin983.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin983
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin988.spl~ THEN BEGIN
COPY_EXISTING ~spin988.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin988
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin990.spl~ THEN BEGIN
COPY_EXISTING ~spin990.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin990
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin999.spl~ THEN BEGIN
COPY_EXISTING ~spin999.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin999
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~sppr105.spl~ THEN BEGIN
COPY_EXISTING ~sppr105.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = sppr105
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~sppr208.spl~ THEN BEGIN
COPY_EXISTING ~sppr208.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = sppr208
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~sppr305.spl~ THEN BEGIN
COPY_EXISTING ~sppr305.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = sppr305
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~sppr989.spl~ THEN BEGIN
COPY_EXISTING ~sppr989.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = sppr989
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi101.spl~ THEN BEGIN
COPY_EXISTING ~spwi101.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi101
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi215.spl~ THEN BEGIN
COPY_EXISTING ~spwi215.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi215
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi306.spl~ THEN BEGIN
COPY_EXISTING ~spwi306.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi306
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi312.spl~ THEN BEGIN
COPY_EXISTING ~spwi312.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi312
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi507.spl~ THEN BEGIN
COPY_EXISTING ~spwi507.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi507
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi959.spl~ THEN BEGIN
COPY_EXISTING ~spwi959.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi959
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwish25.spl~ THEN BEGIN
COPY_EXISTING ~spwish25.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwish25
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwm111.spl~ THEN BEGIN
COPY_EXISTING ~spwm111.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwm111
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwm122.spl~ THEN BEGIN
COPY_EXISTING ~spwm122.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwm122
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwm123.spl~ THEN BEGIN
COPY_EXISTING ~spwm123.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwm123
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwm142.spl~ THEN BEGIN
COPY_EXISTING ~spwm142.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwm142
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwm164.spl~ THEN BEGIN
COPY_EXISTING ~spwm164.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwm164
END
END

/// FA PROTECTS VS STUN ON EE//

ACTION_IF FILE_EXISTS_IN_GAME ~sppr718.spl~ THEN BEGIN
COPY_EXISTING ~sppr718.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = sppr718
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi715.spl~ THEN BEGIN
COPY_EXISTING ~spwi715.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi715
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi816.spl~ THEN BEGIN
COPY_EXISTING ~spwi816.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi816
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi898.spl~ THEN BEGIN
COPY_EXISTING ~spwi898.spl~ ~override~   // 
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi898
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~%sppr325%.spl~ THEN BEGIN
COPY_EXISTING ~%sppr325%.spl~ ~override~   //  Spike Growth - maybe yes, maybe no
  LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 29   // Free action
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = EVAL ~%sppr325%~
END
END

//// FEAR IMMUNITY //

ACTION_IF FILE_EXISTS_IN_GAME ~bdtgaze.spl~ THEN BEGIN  // terrifying gaze
COPY_EXISTING ~bdtgaze.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = bdtgaze
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdneoawe.spl~ THEN BEGIN
COPY_EXISTING ~bdneoawe.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = bdneoawe
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdaurafe.spl~ THEN BEGIN
COPY_EXISTING ~bdaurafe.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = bdaurafe
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~bddragg2.spl~ THEN BEGIN
COPY_EXISTING ~bddragg2.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = bddragg2
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdfear.spl~ THEN BEGIN
COPY_EXISTING ~bdfear.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = bdfear
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdhafear.spl~ THEN BEGIN
COPY_EXISTING ~bdhafear.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = bdhafear
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdgfear.spl~ THEN BEGIN
COPY_EXISTING ~bdgfear.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = bdgfear
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin105.spl~ THEN BEGIN  // innate bhalpower
COPY_EXISTING ~spin105.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin105
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin203.spl~ THEN BEGIN
COPY_EXISTING ~spin203.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin203
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin536.spl~ THEN BEGIN
COPY_EXISTING ~spin536.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin536
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin559.spl~ THEN BEGIN
COPY_EXISTING ~spin559.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin559
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin675.spl~ THEN BEGIN
COPY_EXISTING ~spin675.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin675
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin680.spl~ THEN BEGIN
COPY_EXISTING ~spin680.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin680
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin807.spl~ THEN BEGIN
COPY_EXISTING ~spin807.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin807
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin882.spl~ THEN BEGIN
COPY_EXISTING ~spin882.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin882
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin890.spl~ THEN BEGIN
COPY_EXISTING ~spin890.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin890
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin891.spl~ THEN BEGIN
COPY_EXISTING ~spin891.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin891
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin895.spl~ THEN BEGIN
COPY_EXISTING ~spin895.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin895
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin921.spl~ THEN BEGIN
COPY_EXISTING ~spin921.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin921
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin957.spl~ THEN BEGIN
COPY_EXISTING ~spin957.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin957
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin981.spl~ THEN BEGIN
COPY_EXISTING ~spin981.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin981
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~sppr416.spl~ THEN BEGIN
COPY_EXISTING ~sppr416.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = sppr416
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi125.spl~ THEN BEGIN
COPY_EXISTING ~spwi125.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi125
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi205.spl~ THEN BEGIN
COPY_EXISTING ~spwi205.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi205
END
END


ACTION_IF FILE_EXISTS_IN_GAME ~spwi899.spl~ THEN BEGIN
COPY_EXISTING ~spwi899.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi899
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi956.spl~ THEN BEGIN
COPY_EXISTING ~spwi956.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi956
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~fearaura.spl~ THEN BEGIN
COPY_EXISTING ~fearaura.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = fearaura
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~ohbtgaze.spl~ THEN BEGIN
COPY_EXISTING ~ohbtgaze.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 106   // fear immune
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = ohbtgaze
END
END

// CHAOS & CONFUSION & CHARM //

ACTION_IF FILE_EXISTS_IN_GAME ~bdblun07.spl~ THEN BEGIN
COPY_EXISTING ~bdblun07.spl~ ~override~  // ??
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = bdblun07
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdhamadc.spl~ THEN BEGIN
COPY_EXISTING ~bdhamadc.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = bdhamadc
END
END


ACTION_IF FILE_EXISTS_IN_GAME ~spin503.spl~ THEN BEGIN
COPY_EXISTING ~spin503.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin503
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin674.spl~ THEN BEGIN
COPY_EXISTING ~spin674.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin674
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin704.spl~ THEN BEGIN
COPY_EXISTING ~spin704.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin704
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin839.spl~ THEN BEGIN
COPY_EXISTING ~spin839.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin839
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin883.spl~ THEN BEGIN
COPY_EXISTING ~spin883.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin883
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin910.spl~ THEN BEGIN
COPY_EXISTING ~spin975.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin910
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin975.spl~ THEN BEGIN
COPY_EXISTING ~spin975.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin975
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin976.spl~ THEN BEGIN
COPY_EXISTING ~spin976.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin976
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin980.spl~ THEN BEGIN
COPY_EXISTING ~spin980.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin980
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin985.spl~ THEN BEGIN
COPY_EXISTING ~spin985.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin985
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~sppr102.spl~ THEN BEGIN
COPY_EXISTING ~sppr204.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = sppr102
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~sppr204.spl~ THEN BEGIN
COPY_EXISTING ~sppr204.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = sppr204
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~%sppr311%.spl~ THEN BEGIN
COPY_EXISTING ~%sppr311%.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = EVAL ~%sppr311%~
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~sppr405.spl~ THEN BEGIN
COPY_EXISTING ~sppr405.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = sppr405
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~sppr512.spl~ THEN BEGIN
COPY_EXISTING ~sppr512.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = sppr512
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~sppr709.spl~ THEN BEGIN
COPY_EXISTING ~sppr709.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = sppr709
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~sppr982.spl~ THEN BEGIN
COPY_EXISTING ~sppr982.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = sppr982
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~sppr983.spl~ THEN BEGIN
COPY_EXISTING ~sppr983.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = sppr983
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi104.spl~ THEN BEGIN
COPY_EXISTING ~spwi104.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi104
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi316.spl~ THEN BEGIN
COPY_EXISTING ~spwi316.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi316
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi401.spl~ THEN BEGIN
COPY_EXISTING ~spwi401.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi401
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi411.spl~ THEN BEGIN
COPY_EXISTING ~spwi411.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi411
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi506.spl~ THEN BEGIN
COPY_EXISTING ~spwi506.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi506
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi508.spl~ THEN BEGIN
COPY_EXISTING ~spwi508.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi508
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi509.spl~ THEN BEGIN
COPY_EXISTING ~spwi509.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi509
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi929.spl~ THEN BEGIN
COPY_EXISTING ~spwi929.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi929
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi930.spl~ THEN BEGIN
COPY_EXISTING ~spwi930.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi930
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi943.spl~ THEN BEGIN
COPY_EXISTING ~spwi943.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi943
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwm162.spl~ THEN BEGIN
COPY_EXISTING ~spwm162.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwm162
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwm186.spl~ THEN BEGIN
COPY_EXISTING ~spwm186.spl~ ~override~  
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 41     // Chaotic commands
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwm186
END
END

/// DEATH IMMUNITY //

ACTION_IF FILE_EXISTS_IN_GAME ~spin681.spl~ THEN BEGIN
COPY_EXISTING ~spin681.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 8
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin681
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin789.spl~ THEN BEGIN
COPY_EXISTING ~spin789.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 8
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin789
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin961.spl~ THEN BEGIN
COPY_EXISTING ~spin961.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 8
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin961
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spin991.spl~ THEN BEGIN
COPY_EXISTING ~spin991.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 8
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spin991
END
END
 
/* ACTION_IF FILE_EXISTS_IN_GAME ~sppr719.spl~ THEN BEGIN  // DW vs FoD
COPY_EXISTING ~sppr719.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 8
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = sppr719
END
END */

/* ACTION_IF FILE_EXISTS_IN_GAME ~spwi713.spl~ THEN BEGIN  // Death Ward vs FoD...
COPY_EXISTING ~spwi713.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 8
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi713
END
END */

ACTION_IF FILE_EXISTS_IN_GAME ~spwi817.spl~ THEN BEGIN
COPY_EXISTING ~spwi817.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 8
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi817
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi912.spl~ THEN BEGIN
COPY_EXISTING ~spwi912.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 8
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi912
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi913.spl~ THEN BEGIN
COPY_EXISTING ~spwi913.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 8
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi913
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi960.spl~ THEN BEGIN
COPY_EXISTING ~spwi960.spl~ ~override~   
LPF ADD_SPELL_EFFECT
	INT_VAR
	opcode			= 324
	target			= 2
	power			= 0
	savingthrow     = 0
	parameter1      = 8
	parameter2		= 110
	duration        = 1
	timing			= 0
	insert_point    = 0
	STR_VAR
	resource        = spwi960
END
END


//////////////////SPELL REV CHANGES to DO// 

/*spdr101 - druid chromatic orb - magic damage + sideeffects
~%sppr121%~ - obscuring mist (blindess, extra senses)
sppr704 - nature's beauty ?? Tue seeing
sppr710 - holy word deaf; probably irrelevant
sppr715 - unholy word deaf ditto aboe
spwi101 is grease - add neg fire res to humanoids  so you can play a DD with fire bonus
spwi106 - fog??
spwi118 - chrom orb // probably skip
spwi125 spook - True Seeing
spwi223 - sound burst (deaf) irrelevant */



///// REGEXP on this CAN BE EDGY; there is likely to be bugs with this...///
////POISON & FEAR itm////

 COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
 LPF CLONE_EFFECT 
 INT_VAR 
 match_opcode = 101
 match_parameter2 = 24 
 opcode = 328
 parameter2 = 106
 special = 1
 silent = 1
 timing = 2
 END   END
 BUT_ONLY_IF_IT_CHANGES 
 
  COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~
  LPF CLONE_EFFECT 
 INT_VAR 
 match_opcode = 101
 match_parameter2 = 25 // poison
 opcode = 173
 parameter1 = 100
 silent = 1
 timing = 2
 END
 BUT_ONLY_IF_IT_CHANGES  

 ////POISON & FEAR spl///
 
 COPY_EXISTING_REGEXP GLOB ~.*\.spl~ ~override~
 LPF CLONE_EFFECT 
 INT_VAR 
 match_opcode = 101
 match_parameter2 = 24 //  fear
 opcode = 328
 parameter2 = 106
 special = 1
 silent = 1
 END 
 BUT_ONLY_IF_IT_CHANGES
 
COPY_EXISTING_REGEXP GLOB ~.*\.spl~ ~override~
  LPF CLONE_EFFECT 
 INT_VAR 
 match_opcode = 101
 match_parameter2 = 25 // poison
 opcode = 173
 parameter1 = 100
 silent = 1
 END
 BUT_ONLY_IF_IT_CHANGES 
 
 
//////////FREE ACTION, shouldn't care about spls?? will be wonky...////

 COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~
 PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
 LPF CLONE_EFFECT 
 INT_VAR 
 match_opcode = 163
 opcode = 328
 parameter2 = 29
 special = 1
 timing = 2
 silent = 1
 END     END
 BUT_ONLY_IF_IT_CHANGES 

// 1pp fixes

DEFINE_ACTION_MACRO ~Locations~ BEGIN
// for weapons
OUTER_SET wgrey = 16
OUTER_SET wteal = 17
OUTER_SET wpink = 18
OUTER_SET wyellow = 19
OUTER_SET wred = 20
OUTER_SET wblue = 21
OUTER_SET wgreen = 22
// for helmets
OUTER_SET hgrey = 48
OUTER_SET hteal = 49
OUTER_SET hpink = 50
OUTER_SET hyellow = 51
OUTER_SET hred = 52
OUTER_SET hblue = 53
OUTER_SET hgreen = 54
// for shields
OUTER_SET sgrey = 32
OUTER_SET steal = 33
OUTER_SET spink = 34
OUTER_SET syellow = 35
OUTER_SET sred = 36
OUTER_SET sblue = 37
OUTER_SET sgreen = 38
// for armour
OUTER_SET agrey = 0
OUTER_SET ateal = 1
OUTER_SET apink = 2
OUTER_SET ayellow = 3
OUTER_SET ared = 4
OUTER_SET ablue = 5
OUTER_SET agreen = 6
END

DEFINE_PATCH_MACRO ~clear~ BEGIN
SET opcode_to_delete = 7
LAUNCH_PATCH_MACRO DELETE_ITEM_EQEFFECT
SET opcode_to_delete = 8
LAUNCH_PATCH_MACRO DELETE_ITEM_EQEFFECT
SET opcode_to_delete = 9
LAUNCH_PATCH_MACRO DELETE_ITEM_EQEFFECT
END

DEFINE_PATCH_MACRO ~colour~ BEGIN
SET opcode = 7      // Set opcode
SET target = 1      // target type
SET timing = 2      // timing type
SET power = 0      // power
SET resist_dispel = 0  // dispel/resitance
SET duration = 0    // duration
SET probability1 = 100  // probability 1
SET probability2 = 0  // probability 2
SPRINT "resource" ""     // resource
SET dicenumber = 0    // dice number 
SET dicesize = 0    // dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0    // saving throw bonus 
SET parameter1 = gradient // set colour gradient
SET parameter2 = location // set location
LAUNCH_PATCH_MACRO ADD_ITEM_EQEFFECT
END

DEFINE_PATCH_MACRO ~pulse~ BEGIN
SET opcode = 9    // Set opcode
SET target = 1      // target type
SET timing = 2      // timing type
SET power = 0      // power
SET resist_dispel = 0  // dispel/resitance
SET duration = 0    // duration
SET probability1 = 100  // probability 1
SET probability2 = 0  // probability 2
SPRINT "resource" ""     // resource
SET dicenumber = 0    // dice number 
SET dicesize = 0    // dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0    // saving throw bonus 
SET setrgb = (setb << 24)+(setg << 16)+(setr << 8) // Set RGB
SET parameter1 = setrgb
SET settwo = (speed << 16)+(location) // Set location and speed
SET parameter2 = settwo
LAUNCH_PATCH_MACRO ADD_ITEM_EQEFFECT
END

DEFINE_PATCH_MACRO ~glow~ BEGIN
SET opcode = 8    // Set opcode
SET target = 1      // target type
SET timing = 2      // timing type
SET power = 0      // power
SET resist_dispel = 0  // dispel/resitance
SET duration = 0    // duration
SET probability1 = 100  // probability 1
SET probability2 = 0  // probability 2
SPRINT "resource" ""     // resource
SET dicenumber = 0    // dice number 
SET dicesize = 0    // dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0    // saving throw bonus 
SET setrgb = (setb << 24)+(setg << 16)+(setr << 8) // Set RGB
SET parameter1 = setrgb
SET parameter2 = location // set location
LAUNCH_PATCH_MACRO ADD_ITEM_EQEFFECT
END

// Protection from Missiles and Physical Mirror projectile fixes
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1arow01.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1arow02.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1arow03.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1arow04.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1arow05.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1arow07.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1arow10.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1arow11.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1arow15.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1axe05.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1axe08.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1axe09.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1axe10.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1axe16.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1bolt01.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1bolt02.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1bolt03.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1bolt04.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1bolt05.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1bolt06.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1bolt09.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1bull02.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1bull03.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1bull04.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1bull05.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1bull06.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1dagg05.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1dagg11.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1dagg12.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1dagg16.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1dart01.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1dart02.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1dart03.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1dart04.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1dart05.PRO~
ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1dart08.PRO~

ACTION_IF (FILE_EXISTS_IN_GAME ~sppr613.spl~) THEN BEGIN
COPY_EXISTING ~sppr613.spl~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
SET "loop" = 1
WHILE (%loop% < 31) BEGIN

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = 55 // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow01% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow02% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow03% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow04% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
  
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow07% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow10% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow11% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow15% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1axe05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1axe08% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1axe09% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1axe10% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1axe16% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt01% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt02% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt03% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt04% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt06% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt09% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bull02% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bull03% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bull04% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bull05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bull06% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dagg05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dagg11% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dagg12% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dagg16% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart01% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart02% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart03% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart04% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (120 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart08% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET "loop" = %loop% + 1

END
END
BUT_ONLY_IF_IT_CHANGES
END

ACTION_IF (FILE_EXISTS_IN_GAME ~spwi311.spl~) THEN BEGIN
COPY_EXISTING ~spwi311.spl~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
SET "loop" = 1
WHILE (%loop% < 37) BEGIN
  
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = 55 // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow01% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow02% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow03% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow04% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
  
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow07% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow10% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow11% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow15% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1axe05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1axe08% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1axe09% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1axe10% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1axe16% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt01% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt02% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt03% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt04% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt06% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt09% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bull02% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bull03% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bull04% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bull05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bull06% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dagg05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dagg11% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dagg12% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dagg16% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart01% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart02% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart03% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart04% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart08% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET "loop" = %loop% + 1

END
END
BUT_ONLY_IF_IT_CHANGES
END

ACTION_IF (FILE_EXISTS_IN_GAME ~spra303.spl~) THEN BEGIN
COPY_EXISTING ~spra303.spl~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
SET "loop" = 1
WHILE (%loop% < 37) BEGIN
  
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = 55 // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow01% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow02% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow03% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow04% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
  
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow07% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow10% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow11% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1arow15% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1axe05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1axe08% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1axe09% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1axe10% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1axe16% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt01% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt02% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt03% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt04% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt06% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bolt09% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bull02% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
 
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bull03% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bull04% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bull05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1bull06% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dagg05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dagg11% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dagg12% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dagg16% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart01% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart02% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart03% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart04% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart05% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
SET opcode = 83			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 3	// dispel/resitance
SET duration = (84 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = (%1dart08% - 1) // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT

SET "loop" = %loop% + 1

END
END
BUT_ONLY_IF_IT_CHANGES
END


// Spell Deflection fixes
ACTION_IF FILE_EXISTS_IN_GAME ~sppr701.spl~ THEN BEGIN
COPY_EXISTING ~sppr701.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
  SET opcode = 201			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 9			// power
SET resist_dispel = 2	// dispel/resitance
SET duration = 60		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "sppr701b" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 100 // param1
SET parameter2 = 1 // param2
SET header = 1
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi318.spl~ THEN BEGIN
COPY_EXISTING ~spwi318.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
  SET opcode = 201			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 3			// power
SET resist_dispel = 2	// dispel/resitance
SET duration = 300		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "spwi318b" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 6 // param1
SET parameter2 = 1 // param2
SET header = 1
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi522.spl~ THEN BEGIN
COPY_EXISTING ~spwi522.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
  SET opcode = 201			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 5			// power
SET resist_dispel = 2	// dispel/resitance
SET duration = 300		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "spwi522b" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 9 // param1
SET parameter2 = 1 // param2
SET header = 1
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi618.spl~ THEN BEGIN
COPY_EXISTING ~spwi618.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
  SET opcode = 201			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 6			// power
SET resist_dispel = 2	// dispel/resitance
SET duration = 300		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "spwi618b" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 9 // param1
SET parameter2 = 1 // param2
SET header = 1
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi618b.spl~ THEN BEGIN
COPY_EXISTING ~spwi618b.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
  SET opcode = 321			// Set opcode
SET target = 1			// target type
SET timing = 1			// timing type
SET power = 0			// power
SET resist_dispel = 0	// dispel/resitance
SET duration = 0		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "spwi522" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 0 // param1
SET parameter2 = 0 // param2
SET header = 1
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi701.spl~ THEN BEGIN
COPY_EXISTING ~spwi701.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
  SET opcode = 201			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 7			// power
SET resist_dispel = 2	// dispel/resitance
SET duration = 300		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "spwi701b" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 12 // param1
SET parameter2 = 1 // param2
SET header = 1
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi902.spl~ THEN BEGIN
COPY_EXISTING ~spwi902.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
  SET "loop" = 1
  WHILE (%loop% < 34) BEGIN
  SET opcode = 201			// Set opcode
SET target = 1			// target type
SET timing = 0			// timing type
SET power = 5			// power
SET resist_dispel = 2	// dispel/resitance
SET duration = (102 + (%loop% * 6))		// duration
SET probability1 = 100	// probability 1
SET probability2 = 0	// probability 2
SPRINT "resource" "spwi902b" 		// resource
SET dicenumber = 0		// dice number 
SET dicesize = 0		// dice size
SET savingthrow = 0   // saving throw
SET savebonus = 0		// saving throw bonus 
SET parameter1 = 100 // param1
SET parameter2 = 1 // param2
SET header = %loop%
LAUNCH_PATCH_MACRO ADD_SPELL_EFFECT
SET "loop" = %loop% + 1
END
END
END


// 1pp graphical effects
ACTION_IF (FILE_EXISTS_IN_GAME ~SPWI317.SPL~) THEN BEGIN
  COPY_EXISTING ~SPWI317.SPL~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    READ_LONG  0x6a "fx_off"
    READ_SHORT 0x6e "fx_idx"
    READ_SHORT 0x70 "fx_num"
    PATCH_IF (fx_off > 0x71) BEGIN
      FOR (index = fx_idx ; index < fx_num ; index = index + 1) BEGIN
        READ_SHORT ("%fx_off%" +        ("%index%" * 0x30)) "opcode"
        READ_ASCII ("%fx_off%" + 0x14 + ("%index%" * 0x30)) "resref"
        PATCH_IF (("%opcode%" = 215) AND ("%resref%" STRING_EQUAL_CASE "ICARMOR"))  BEGIN
          WRITE_ASCII ("%fx_off%" + 0x14 + ("%index%" * 0x30)) ~1WDGARMR~ #8
        END
      END
    END
  END
  BUT_ONLY_IF_IT_CHANGES
END

ACTION_IF (FILE_EXISTS_IN_GAME ~SPWI414.SPL~) THEN BEGIN
  COPY_EXISTING ~SPWI414.SPL~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    READ_LONG  0x6a "fx_off"
    READ_SHORT 0x6e "fx_idx"
    READ_SHORT 0x70 "fx_num"
    PATCH_IF (fx_off > 0x71) BEGIN
      FOR (index = fx_idx ; index < fx_num ; index = index + 1) BEGIN
        READ_SHORT ("%fx_off%" +        ("%index%" * 0x30)) "opcode"
        READ_ASCII ("%fx_off%" + 0x14 + ("%index%" * 0x30)) "resref"
        PATCH_IF (("%opcode%" = 215) AND ("%resref%" STRING_EQUAL_CASE "SPSARMOR"))  BEGIN
          WRITE_ASCII ("%fx_off%" + 0x14 + ("%index%" * 0x30)) ~1WDSARMR~ #8
        END
      END
    END
  END
  BUT_ONLY_IF_IT_CHANGES
END

ACTION_IF (FILE_EXISTS_IN_GAME ~DVPR119D.spl~) BEGIN
  COPY_EXISTING ~DVPR119D.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    REPLACE_TEXTUALLY CASE_INSENSITIVE ~ICMAGICH~ ~1WDCMDAM~
  END
  BUT_ONLY_IF_IT_CHANGES
END

ACTION_IF (FILE_EXISTS_IN_GAME ~DVPR219D.spl~) BEGIN
  COPY_EXISTING ~DVPR219D.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    REPLACE_TEXTUALLY CASE_INSENSITIVE ~ICMAGICH~ ~1WDCMDAM~
  END
  BUT_ONLY_IF_IT_CHANGES
END

ACTION_IF (FILE_EXISTS_IN_GAME ~DVPR321D.spl~) BEGIN
  COPY_EXISTING ~DVPR321D.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    REPLACE_TEXTUALLY CASE_INSENSITIVE ~ICMAGICH~ ~1WDCMDAM~
  END
  BUT_ONLY_IF_IT_CHANGES
END

ACTION_IF (FILE_EXISTS_IN_GAME ~DVPR414D.spl~) BEGIN
  COPY_EXISTING ~DVPR414D.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    REPLACE_TEXTUALLY CASE_INSENSITIVE ~ICMAGICH~ ~1WDCMDAM~
  END
  BUT_ONLY_IF_IT_CHANGES
END

ACTION_IF (FILE_EXISTS_IN_GAME ~DVPR510D.spl~) BEGIN
  COPY_EXISTING ~DVPR510D.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    REPLACE_TEXTUALLY CASE_INSENSITIVE ~ICMAGICH~ ~1WDCMDAM~
  END
  BUT_ONLY_IF_IT_CHANGES
END

ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1arow15.PRO~

ACTION_IF (FILE_EXISTS_IN_GAME ~dvenarow.ITM~) THEN BEGIN
COPY_EXISTING ~dvenarow.ITM~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    READ_LONG  0x64 "abil_off" ELSE 0
    READ_SHORT 0x68 "abil_num" ELSE 0
    PATCH_IF (abil_off > 0x71) BEGIN
      FOR (index = 0; index < abil_num; index = index + 1) BEGIN
        READ_SHORT ("%abil_off%" + 0x2a + (0x38 * "%index%")) "proj"
        LOOKUP_IDS_SYMBOL_OF_INT projectile projectl %proj% - 1
        PATCH_IF ("%projectile%" STRING_EQUAL_CASE "ARROW") BEGIN
          WRITE_SHORT ("%abil_off%" + 0x2a + (0x38 * "%index%")) ~%1arow15%~
        END
      END
    END
	  END
  BUT_ONLY_IF_IT_CHANGES
  END

ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1bolt09.PRO~

ACTION_IF (FILE_EXISTS_IN_GAME ~dvenbolt.ITM~) THEN BEGIN
COPY_EXISTING ~dvenbolt.ITM~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    READ_LONG  0x64 "abil_off" ELSE 0
    READ_SHORT 0x68 "abil_num" ELSE 0
    PATCH_IF (abil_off > 0x71) BEGIN
      FOR (index = 0; index < abil_num; index = index + 1) BEGIN
        READ_SHORT ("%abil_off%" + 0x2a + (0x38 * "%index%")) "proj"
        LOOKUP_IDS_SYMBOL_OF_INT projectile projectl %proj% - 1
        PATCH_IF ("%projectile%" STRING_EQUAL_CASE "BOLT") BEGIN
          WRITE_SHORT ("%abil_off%" + 0x2a + (0x38 * "%index%")) ~%1bolt09%~
        END
      END
    END
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 186	// colour index
	SET location = wpink		// location
	LAUNCH_PATCH_MACRO ~colour~
	  END
  BUT_ONLY_IF_IT_CHANGES
  END

ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1bull05.PRO~

ACTION_IF (FILE_EXISTS_IN_GAME ~dvenbull.ITM~) THEN BEGIN
COPY_EXISTING ~dvenbull.ITM~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    READ_LONG  0x64 "abil_off" ELSE 0
    READ_SHORT 0x68 "abil_num" ELSE 0
    PATCH_IF (abil_off > 0x71) BEGIN
      FOR (index = 0; index < abil_num; index = index + 1) BEGIN
        READ_SHORT ("%abil_off%" + 0x2a + (0x38 * "%index%")) "proj"
        LOOKUP_IDS_SYMBOL_OF_INT projectile projectl %proj% - 1
        PATCH_IF ("%projectile%" STRING_EQUAL_CASE "BULLET") BEGIN
          WRITE_SHORT ("%abil_off%" + 0x2a + (0x38 * "%index%")) ~%1bull05%~
        END
      END
    END
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 148	// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	  END
  BUT_ONLY_IF_IT_CHANGES
  END

ADD_PROJECTILE      ~1pp/additions/projectiles_1pp/1dart01.PRO~

ACTION_IF (FILE_EXISTS_IN_GAME ~dvendart.ITM~) THEN BEGIN
COPY_EXISTING ~dvendart.ITM~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    READ_LONG  0x64 "abil_off" ELSE 0
    READ_SHORT 0x68 "abil_num" ELSE 0
    PATCH_IF (abil_off > 0x71) BEGIN
      FOR (index = 0; index < abil_num; index = index + 1) BEGIN
        READ_SHORT ("%abil_off%" + 0x2a + (0x38 * "%index%")) "proj"
        LOOKUP_IDS_SYMBOL_OF_INT projectile projectl %proj% - 1
        PATCH_IF ("%projectile%" STRING_EQUAL_CASE "DART") BEGIN
          WRITE_SHORT ("%abil_off%" + 0x2a + (0x38 * "%index%")) ~%1dart01%~
        END
      END
    END
	  END
  BUT_ONLY_IF_IT_CHANGES
  END