ACTION_IF spell_protections=1 BEGIN
  ACTION_FOR_EACH resource IN
    ~spcl231~
    ~spin112~
    ~sppr303~
    ~spwi302~
    ~spwi326~
  BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~%resource%.spl~) BEGIN
      COPY_EXISTING ~%resource%.spl~ ~override\%resource%.spl~
      PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
        LPF ALTER_EFFECT INT_VAR silent = 1 power = 3 END
      END
    BUT_ONLY
    END
  END
END